(ns extract-catalog
  "Extract metadata from PhotoCraft's Rust CommandSpec registry and control protocol.
   Usage: clojure -M:dev -m extract-catalog /path/to/photocraft"
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]))

(defn- matches [pattern text]
  (let [m (.matcher (java.util.regex.Pattern/compile pattern
                       java.util.regex.Pattern/DOTALL) text)]
    (loop [out []]
      (if (.find m)
        (recur (conj out (mapv #(.group m %) (range (inc (.groupCount m))))))
        out))))

(defn- entries [file]
  (let [text (slurp file)
        ;; Rust macro invocation: first two positional arguments are string literals.
        macros (for [[_ id label] (matches "cmd!\\s*\\(\\s*\"([^\"]+)\"\\s*,\\s*\"([^\"]+)\"" text)]
                 {:id id :label label :params-doc (or (some->> (matches (str "cmd!\\s*\\(\\s*\""
                        (java.util.regex.Pattern/quote id)
                        "\".*?\\b(r#+\".*?\"#+|\"\\{[^\"]*\\}\")\\s*,") text)
                        first second) "See upstream CommandSpec")})
        structs (for [[_ id label params] (matches
                        "CommandSpec\\s*\\{\\s*id:\\s*\"([^\"]+)\"\\s*,\\s*label:\\s*\"([^\"]+)\".*?params:\\s*(r#+\".*?\"#+|\"[^\"]*\")\\s*,"
                        text)]
                  {:id id :label label :params-doc params})]
    (concat macros structs)))

(defn -main [& [root]]
  (when-not root (throw (ex-info "Pass PhotoCraft source root" {})))
  (let [dir (io/file root "crates/engine/src")
        files (filter #(str/ends-with? (.getName %) ".rs") (file-seq dir))
        commands (->> files (mapcat entries) (distinct) (sort-by :id) vec)
        methods ["engine.execute" "engine.commands" "ui.inspect" "ui.set"
                 "ui.menu.invoke" "ui.menu.list" "ui.dialog.open" "ui.dialog.set"
                 "ui.dialog.confirm" "ui.dialog.cancel" "ui.dialog.apply"
                 "ui.window.open" "ui.window.close" "ui.pointer" "ui.key" "ui.type"
                 "ui.resize" "ui.gpu.simulateLoss" "ui.screenshot" "ui.focus"
                 "ui.context.choose" "app.open" "app.save" "app.quit"]
        output {:source "photocraft/crates/engine/src (CommandSpec and cmd! declarations)"
                :control-source "photocraft/docs/control-protocol.md"
                :commands commands :methods methods}]
    (spit "resources/hive_photocraft/catalog.edn"
          (str ";; Generated by dev/extract_catalog.clj; do not edit by hand.\n"
               (pr-str output) "\n"))
    (println "Extracted" (count commands) "commands and" (count methods) "control methods")))
